spring:
  redis:
    password: "123456"
    database: 0
    cluster:
      nodes: 127.0.0.1:6379 # 集群模式下 redis 地址,多个用逗号分隔
    lettuce:
      cluster:
        refresh:
          period: 2000 # 定时刷新周期
          adaptive: true # 自适应拓扑刷新


